"""Declares the 15 navigable modules: title, icon, page file, section, and
which milestone implements them. main.py builds st.navigation from this
list, so adding a module later is a config change, not a nav rewrite.

Titles/order match the official Capstone Portal Functional Requirements
(docs/spec.md) exactly — module keys/page filenames are our own internal
naming and don't need to match."""

MODULES = [
    {
        "key": "dashboard",
        "title": "Dashboard",
        "icon": "🏠",
        "page": "app/pages/dashboard.py",
        "section": "Home",
        "milestone": "MS-02",
        "default": True,
        "implemented": True,
    },
    {
        "key": "text_intelligence",
        "title": "Text Intelligence",
        "icon": "📝",
        "page": "app/pages/text_intelligence.py",
        "section": "Intelligence",
        "milestone": "MS-04",
        "implemented": True,
    },
    {
        "key": "image_understanding",
        "title": "Image Intelligence",
        "icon": "🖼️",
        "page": "app/pages/image_understanding.py",
        "section": "Intelligence",
        "milestone": "MS-05",
        "implemented": True,
    },
    {
        "key": "document_analyzer",
        "title": "Document Analyzer",
        "icon": "📄",
        "page": "app/pages/document_analyzer.py",
        "section": "Intelligence",
        "milestone": "MS-06",
    },
    {
        "key": "prompt_optimizer",
        "title": "Prompt Optimizer",
        "icon": "✨",
        "page": "app/pages/prompt_optimizer.py",
        "section": "Optimization",
        "milestone": "MS-09",
    },
    {
        "key": "tokens",
        "title": "Token Explorer",
        "icon": "🔤",
        "page": "app/pages/tokens.py",
        "section": "Optimization",
        "milestone": "MS-07",
    },
    {
        "key": "embeddings",
        "title": "Embedding Explorer",
        "icon": "🧭",
        "page": "app/pages/embeddings.py",
        "section": "Optimization",
        "milestone": "MS-08",
    },
    {
        "key": "model_explorer",
        "title": "Model Explorer",
        "icon": "🧩",
        "page": "app/pages/model_explorer.py",
        "section": "Explorers",
        "milestone": "MS-10",
    },
    {
        "key": "pipeline_explorer",
        "title": "Pipeline Explorer",
        "icon": "🔗",
        "page": "app/pages/pipeline_explorer.py",
        "section": "Explorers",
        "milestone": "MS-10",
    },
    {
        "key": "visualizations",
        "title": "Visualization Dashboard",
        "icon": "📊",
        "page": "app/pages/visualizations.py",
        "section": "Explorers",
        "milestone": "MS-10",
    },
    {
        "key": "responsible_ai",
        "title": "Responsible AI Dashboard",
        "icon": "🛡️",
        "page": "app/pages/responsible_ai.py",
        "section": "Governance",
        "milestone": "MS-11",
    },
    {
        "key": "infrastructure",
        "title": "AI Infrastructure Explorer",
        "icon": "🖥️",
        "page": "app/pages/infrastructure.py",
        "section": "Governance",
        "milestone": "MS-12",
    },
    {
        "key": "settings",
        "title": "Settings",
        "icon": "⚙️",
        "page": "app/pages/settings.py",
        "section": "Ops",
        "milestone": "MS-12",
    },
    {
        "key": "export_reports",
        "title": "Export Reports",
        "icon": "📤",
        "page": "app/pages/export_reports.py",
        "section": "Ops",
        "milestone": "MS-12",
    },
    {
        "key": "history",
        "title": "History",
        "icon": "🕘",
        "page": "app/pages/history.py",
        "section": "Ops",
        "milestone": "MS-12",
    },
]
